name: pawtrack
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/paw_logo.jpg
    - assets/images/pet_home.png
